# Generated by Django 2.2.7 on 2019-12-04 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ph_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatuschangelog',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ph_orders.Order'),
            preserve_default=False,
        ),
    ]
