# Generated by Django 2.2.7 on 2019-11-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100, verbose_name='название товара')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='описание')),
                ('price', models.FloatField(verbose_name='цена')),
                ('left_in_stock', models.IntegerField(default=1, verbose_name='осталось на складе')),
                ('prime_cost', models.FloatField(blank=True, verbose_name='себестоимость')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', to='ph_products.Category', verbose_name='категория')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('is_main', models.BooleanField(default=False)),
                ('alt', models.TextField(default='Product picture', max_length=100)),
                ('id_goods', models.ForeignKey(on_delete='CASCADE', related_name='photos', to='ph_products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.TextField(max_length=100)),
                ('size', models.TextField(choices=[('XXS', 'XXSmall'), ('XS', 'XSmall'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'XLarge'), ('XXL', 'XXLarge'), ('NO', 'Without size')], max_length=30)),
                ('left_in_stock', models.IntegerField(default=1, verbose_name='осталось на складе')),
                ('id_goods', models.ForeignKey(on_delete='CASCADE', related_name='modifications', to='ph_products.Product')),
            ],
        ),
    ]
