# Generated by Django 2.2.7 on 2019-12-04 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ph_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AlterModelOptions(
            name='productmodification',
            options={'verbose_name': 'модификация', 'verbose_name_plural': 'модификации товара'},
        ),
        migrations.AlterModelOptions(
            name='productphoto',
            options={'verbose_name': 'фото товара', 'verbose_name_plural': 'фото товаров'},
        ),
    ]
