# Generated by Django 2.2.6 on 2019-12-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ph_products', '0002_auto_20191204_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodification',
            old_name='id_goods',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productphoto',
            old_name='id_goods',
            new_name='product',
        ),
        migrations.AddField(
            model_name='category',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='prime_cost',
            field=models.FloatField(blank=True, default=0, verbose_name='себестоимость'),
        ),
    ]
