# Generated by Django 2.2.6 on 2019-10-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Piter_Hipster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Count', models.IntegerField()),
                ('Price', models.FloatField()),
                ('id_goods', models.ForeignKey(on_delete='CASCADE', to='Piter_Hipster.Goods')),
                ('id_order', models.ForeignKey(on_delete='CASCADE', to='Piter_Hipster.Orders')),
            ],
        ),
    ]
