# Generated by Django 2.2.6 on 2019-10-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Piter_Hipster', '0002_goodsinorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='isMain',
            field=models.BooleanField(default=False),
        ),
    ]
