# Generated by Django 2.2.6 on 2019-10-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Piter_Hipster', '0004_modifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifications',
            name='size',
            field=models.TextField(choices=[('XXS', 'XXSmall'), ('XS', 'XSmall'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'XLarge'), ('XXL', 'XXLarge'), ('NO', 'Without size')], max_length=30),
        ),
    ]
