# Generated by Django 2.2.6 on 2019-10-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Piter_Hipster', '0005_auto_20191030_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='alt',
            field=models.TextField(default='picture', max_length=100),
        ),
    ]
