# Generated by Django 2.2.7 on 2019-12-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Piter_Hipster', '0006_photos_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinorders',
            name='Count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='goodsinorders',
            name='id_order',
            field=models.ForeignKey(on_delete='CASCADE', related_name='goodsInOrders', to='Piter_Hipster.Orders'),
        ),
        migrations.AlterField(
            model_name='modifications',
            name='id_goods',
            field=models.ForeignKey(on_delete='CASCADE', related_name='modifications', to='Piter_Hipster.Goods'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('В корзине', 'В корзине'), ('Создан', 'Создан'), ('Согласован', 'Согласован'), ('Оплачен', 'Оплачен'), ('В пути', 'В пути'), ('Завершен', 'Завершен')], default='В корзине', max_length=30),
        ),
        migrations.AlterField(
            model_name='photos',
            name='id_goods',
            field=models.ForeignKey(on_delete='CASCADE', related_name='photos', to='Piter_Hipster.Goods'),
        ),
    ]
